import React, { useEffect, useState } from 'react';
import api, { errorMessage } from '../api/api';
import { useAuth } from './AuthContext';
export default function Catalog({ categoriesOnly = false }) {
 const { can } = useAuth();
 const [items,setItems]=useState([]), [categories,setCategories]=useState([]), [query,setQuery]=useState(''), [filter,setFilter]=useState(''), [editor,setEditor]=useState(null), [error,setError]=useState(''), [notice,setNotice]=useState(''), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false);
 const entity=categoriesOnly?'Category':'Product';
 async function load(){setLoading(true);setError('');try{const responses=await Promise.all([categoriesOnly?api.post('Category/getallcategories'):api.get('Products/getall'),!categoriesOnly&&can('Category.Get')?api.post('Category/getallcategories'):Promise.resolve(null)]);setItems(categoriesOnly?responses[0].data.data:responses[0].data);if(responses[1])setCategories(responses[1].data.data);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{load();
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[categoriesOnly]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');const data=Object.fromEntries(new FormData(e.currentTarget));if(!categoriesOnly)['categoryId','unitPrice','unitsInStock'].forEach(k=>data[k]=Number(data[k]));if(editor.id)data.id=editor.id;try{await api.post(categoriesOnly?`Category/${editor.id?'updatecategory':'addcategory'}`:`Products/${editor.id?'update':'add'}`,data);setEditor(null);await load();setNotice('Kayıt kaydedildi.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(item){if(!window.confirm(`“${item.productName||item.categoryName}” silinsin mi?`))return;setBusy(true);setNotice('');setError('');try{await api.delete(`${categoriesOnly?'Category':'Products'}/${item.id}`);await load();setNotice('Kayıt silindi.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const visible=items.filter(i=>(i.productName||i.categoryName).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))&&(!filter||String(i.categoryId)===filter));
 return <><div className="page-heading"><div><span className="eyebrow">KATALOG</span><h1>{categoriesOnly?'Kategoriler':'Ürünler'}</h1><p className="muted">{categoriesOnly?'Kataloğunuzu düzenleyen kategoriler.':'Ürün, fiyat ve stok bilgilerini keşfedin.'}</p></div>{can(`${entity}.Add`)&&<button disabled={busy} onClick={()=>{setEditor({});setError('');}}>+ {categoriesOnly?'Kategori':'Ürün'} ekle</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 {editor&&<section className="panel"><h2>{editor.id?'Kaydı düzenle':'Yeni kayıt'}</h2><form onSubmit={save}><div className="form-grid"><label>{categoriesOnly?'Kategori adı':'Ürün adı'}<input name={categoriesOnly?'categoryName':'productName'} required minLength={categoriesOnly?1:2} maxLength={categoriesOnly?100:30} defaultValue={editor.categoryName||editor.productName||''}/></label>{!categoriesOnly&&<><label>Kategori{can('Category.Get')?<select name="categoryId" required defaultValue={editor.categoryId||''}><option value="">Kategori seçin</option>{categories.map(c=><option key={c.id} value={c.id}>{c.categoryName}</option>)}</select>:<input name="categoryId" type="number" min="1" required defaultValue={editor.categoryId}/>}</label><label>Birim açıklaması<input name="quantityPerUnit" defaultValue={editor.quantityPerUnit||''}/></label><label>Birim fiyat<input name="unitPrice" type="number" min="1" step="0.01" required defaultValue={editor.unitPrice}/></label><label>Stok miktarı<input name="unitsInStock" type="number" min="0" max="32767" step="1" required defaultValue={editor.unitsInStock??0}/></label></>}</div><div className="actions"><button disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setEditor(null)}>Vazgeç</button></div></form></section>}
 <section className="panel"><div className="filters"><label>Ara<input placeholder="Ad ile ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{!categoriesOnly&&can('Category.Get')&&<label>Kategori<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tüm kategoriler</option>{categories.map(c=><option key={c.id} value={c.id}>{c.categoryName}</option>)}</select></label>}<button className="secondary" disabled={loading||busy} onClick={load}>Yenile</button></div>{loading?<p role="status">Yükleniyor…</p>:<><p className="muted">{visible.length} kayıt</p><div className="table-wrap"><table><thead><tr><th>Ad</th>{!categoriesOnly&&<><th>Kategori</th><th>Birim</th><th>Fiyat</th><th>Stok</th></>}{(can(`${entity}.Update`)||can(`${entity}.Delete`))&&<th>İşlemler</th>}</tr></thead><tbody>{visible.map(i=><tr key={i.id}><td>{i.productName||i.categoryName}</td>{!categoriesOnly&&<><td>{i.category?.categoryName||categories.find(c=>c.id===i.categoryId)?.categoryName||i.categoryId}</td><td>{i.quantityPerUnit||'—'}</td><td>{new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2}).format(i.unitPrice)}</td><td><span className="badge">{i.unitsInStock===0?'Stok yok':i.unitsInStock}</span></td></>}{(can(`${entity}.Update`)||can(`${entity}.Delete`))&&<td><div className="actions">{can(`${entity}.Update`)&&<button className="secondary" disabled={busy} onClick={()=>{setEditor(i);setError('');}}>Düzenle</button>}{can(`${entity}.Delete`)&&<button className="danger" disabled={busy} onClick={()=>remove(i)}>Sil</button>}</div></td>}</tr>)}</tbody></table></div>{visible.length===0&&<p>Gösterilecek kayıt bulunamadı.</p>}</>}</section></>;
}
